from datetime import date
from calendar import monthrange
from dateutil.relativedelta import relativedelta

from odoo import _, api, fields, models
from odoo.exceptions import UserError
from odoo.tools import float_round


class AccountMove(models.Model):
    _inherit = 'account.move'

    is_accrued_entry = fields.Boolean(
        string='Is Accrued Entry',
        copy=False,
        help="Technical flag set on the entries generated by the accrued "
             "expense feature.",
    )
    accrued_origin_move_id = fields.Many2one(
        'account.move',
        string='Accrued Origin Bill',
        copy=False,
        index=True,
        ondelete='cascade',
    )
    accrued_move_ids = fields.One2many(
        'account.move',
        'accrued_origin_move_id',
        string='Accrued Entries',
    )
    accrued_move_count = fields.Integer(
        string='Accrued Entries Count',
        compute='_compute_accrued_move_count',
    )

    @api.depends('accrued_move_ids')
    def _compute_accrued_move_count(self):
        for move in self:
            move.accrued_move_count = len(move.accrued_move_ids)

    # ------------------------------------------------------------------
    #  UI helper
    # ------------------------------------------------------------------
    def action_view_accrued_entries(self):
        self.ensure_one()
        return {
            'name': _('Accrued Entries'),
            'type': 'ir.actions.act_window',
            'res_model': 'account.move',
            'view_mode': 'list,form',
            'domain': [('id', 'in', self.accrued_move_ids.ids)],
            'context': {'create': False},
        }

    # ------------------------------------------------------------------
    #  Posting hook
    # ------------------------------------------------------------------
    def _post(self, soft=True):
        """
        After posting: for vendor bills with accrued expense lines:

        1. Swap the posted journal item account from expense → accrual
           (using low-level _write to bypass recompute / enterprise locks).
           The bill entry becomes:
               Dr  Accrual Account  (حساب الاستحقاق)
               Cr  Accounts Payable (حساب المورد)

        2. Generate monthly recognition entries:
               Dr  Expense Account  (كل شهر)
               Cr  Accrual Account
        """
        posted = super()._post(soft=soft)

        for move in posted:
            # Skip the monthly recognition entries we generate ourselves.
            # Do NOT skip if accrued_move_ids is non-empty – that can happen
            # after a reset-to-draft + re-post cycle where leftover posted
            # entries still exist; the line-level guard (accrued_expense_account_id)
            # is the authoritative check for "already processed".
            if move.is_accrued_entry:
                continue
            if move.move_type not in ('in_invoice', 'in_refund'):
                continue

            accrued_lines = move.line_ids.filtered(
                lambda l: l.is_accrued_expense
                and l.accrued_start_date
                and l.accrued_end_date
                and not l.accrued_expense_account_id  # not already processed
            )
            if not accrued_lines:
                continue

            company = move.company_id
            accrued_account = company.accrued_expense_account_id
            journal = company.accrued_expense_journal_id

            if not accrued_account or not journal:
                raise UserError(_(
                    "Please set the Accrued Expense Account and Journal in "
                    "Accounting → Configuration → Settings before posting a "
                    "bill with accrued lines."
                ))

            for line in accrued_lines:
                if line.accrued_end_date < line.accrued_start_date:
                    raise UserError(_(
                        "Accrual End date cannot be before the Start date "
                        "(line: %s).", line.name or ''))

                # ── Swap account on the POSTED journal item ───────────────
                # account_id is a stored-computed field in Odoo 18; after
                # _post() any recomputes have already fired, so _write()
                # here persists without being overridden.
                original_account_id = line.account_id.id
                line._write({
                    'account_id': accrued_account.id,
                    'accrued_expense_account_id': original_account_id,
                })
                # Refresh the ORM cache so the new values are visible in
                # the same transaction.
                line.invalidate_recordset(
                    ['account_id', 'accrued_expense_account_id'])

            move._generate_accrued_entries()

        return posted

    def button_draft(self):
        # 1. Remove ALL accrual recognition entries (draft AND posted).
        #    Posted ones must be reset to draft before they can be deleted.
        accrual_entries = self.accrued_move_ids
        if accrual_entries:
            posted_entries = accrual_entries.filtered(lambda m: m.state == 'posted')
            if posted_entries:
                # Calling super() directly avoids infinite recursion; accrual
                # entries have empty accrued_move_ids so our override is a no-op
                # for them anyway, but using super() is safer.
                super(AccountMove, posted_entries).button_draft()
            accrual_entries.unlink()

        # 2. Reset the bill to draft (Odoo changes state, resets name/ref).
        result = super().button_draft()

        # 3. Now the bill is in DRAFT – use regular write() so that False is
        #    correctly mapped to SQL NULL (using _write with False would send 0,
        #    violating the FK constraint on accrued_expense_account_id).
        for move in self:
            for line in move.line_ids.filtered(
                    lambda l: l.accrued_expense_account_id):
                original_id = line.accrued_expense_account_id.id
                line.write({
                    'account_id': original_id,
                    'accrued_expense_account_id': False,
                })

        return result

    # ------------------------------------------------------------------
    #  Generation
    # ------------------------------------------------------------------
    def _generate_accrued_entries(self):
        """Create monthly recognition entries for all accrued lines on this bill."""
        self.ensure_one()
        company = self.company_id
        accrued_account = company.accrued_expense_account_id
        journal = company.accrued_expense_journal_id

        # Lines that have been swapped (original expense account is stored).
        accrued_lines = self.line_ids.filtered(
            lambda l: l.is_accrued_expense
            and l.accrued_start_date
            and l.accrued_end_date
            and l.accrued_expense_account_id
        )
        if not accrued_lines:
            return

        for line in accrued_lines:
            self._create_accrual_for_line(line, accrued_account, journal)

        # Post any recognition entries whose date has already arrived.
        today = fields.Date.context_today(self)
        self.accrued_move_ids.filtered(
            lambda m: m.state == 'draft' and m.date <= today
        )._post(soft=False)

    def _create_accrual_for_line(self, line, accrued_account, journal):
        """
        Monthly recognition entries for one accrued line:
            Dr  Expense Account  (حساب المصروف — original)
            Cr  Accrual Account  (حساب الاستحقاق)
        """
        self.ensure_one()
        company = self.company_id
        currency = company.currency_id

        # Original expense account (saved before the account swap).
        expense_account = line.accrued_expense_account_id
        # Balance of the line is the same amount, now sitting in the accrual account.
        total = line.balance   # positive (debit) for an in_invoice line

        if currency.is_zero(total):
            return

        Move = self.env['account.move']

        for rec_date, amount in self._accrued_schedule(
                total, line.accrued_start_date, line.accrued_end_date):
            if currency.is_zero(amount):
                continue
            Move.create({
                'move_type': 'entry',
                'journal_id': journal.id,
                'date': rec_date,
                'ref': _('Accrued recognition: %s',
                          line.name or self.name or ''),
                'is_accrued_entry': True,
                'accrued_origin_move_id': self.id,
                'company_id': company.id,
                'line_ids': [
                    # Dr Expense
                    self._accrued_line_vals(expense_account, line.name, amount),
                    # Cr Accrual
                    self._accrued_line_vals(accrued_account, line.name, -amount),
                ],
            })

    def _accrued_line_vals(self, account, name, balance):
        """Return move line vals with a signed balance mapped to debit/credit."""
        return (0, 0, {
            'account_id': account.id,
            'name': name or _('Accrued expense'),
            'debit': balance if balance > 0 else 0.0,
            'credit': -balance if balance < 0 else 0.0,
        })

    def _accrued_schedule(self, total, start, end):
        """Split ``total`` across each calendar month in [start, end].

        Full months receive equal shares.  Partial first / last months are
        prorated by the fraction of the month they cover.

        Algorithm – "equivalent months":
            weight  = days_covered_in_month / days_in_month
                      (1.0 for a complete month, <1.0 for a partial month)
            eq_months   = Σ weight
            monthly_amt = total / eq_months
            month_amt   = monthly_amt × weight

        The last entry absorbs any cent-level rounding difference.
        Recognition date is the last covered day of each month.
        """
        self.ensure_one()
        currency = self.company_id.currency_id

        if (end - start).days < 0:
            return []

        # Build segments: (recognition_date, weight)
        segments = []
        cur = start
        while cur <= end:
            days_in_month = monthrange(cur.year, cur.month)[1]
            month_end = date(cur.year, cur.month, days_in_month)
            period_end = min(month_end, end)
            days_covered = (period_end - cur).days + 1
            weight = days_covered / days_in_month   # 1.0 for a full month
            segments.append((period_end, weight))
            cur = period_end + relativedelta(days=1)

        total_weight = sum(w for _, w in segments)
        if not total_weight:
            return []

        monthly_rate = total / total_weight

        result = []
        allocated = 0.0
        for i, (period_end, weight) in enumerate(segments):
            if i == len(segments) - 1:
                # Last segment absorbs rounding difference
                amount = float_round(
                    total - allocated,
                    precision_rounding=currency.rounding,
                )
            else:
                amount = float_round(
                    monthly_rate * weight,
                    precision_rounding=currency.rounding,
                )
            result.append((period_end, amount))
            allocated += amount

        return result

    # ------------------------------------------------------------------
    #  Scheduler: post recognition entries when their date arrives
    # ------------------------------------------------------------------
    @api.model
    def _cron_post_accrued_entries(self):
        today = fields.Date.context_today(self)
        due = self.search([
            ('is_accrued_entry', '=', True),
            ('state', '=', 'draft'),
            ('date', '<=', today),
        ])
        for move in due:
            try:
                move._post(soft=False)
            except Exception:
                continue
