from . import product_template
from . import product_product
from . import stock_quant
from . import stock_move
from . import stock_move_line
from . import stock_rule
from . import sale_order_line
from . import purchase_order_line
from . import mrp_production
from . import mrp_bom_line
from . import account_move_line
